spring.application.name=springbootbackend
spring.datasource.url=jdbc:mysql://localhost:3306/springbootbackend
spring.datasource.username=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

upload.path=uploads/